/* gps_sim.c -- hal/gps.h over a committed synthetic capture (spec §4.6 GPS=sim, §22.3).
 *
 * A bench driver so the whole firmware runs before the real GPS arrives. It does NOT parse UBX or
 * touch a UART (that is gps_neo6m/gps_m10, plans 07-08, and the §22.3 gps_sim.py byte injector):
 * it replays the committed SIM_FIXES[] (sim_capture.h) DIRECTLY, one gps_fix_t at a time, pacing
 * them at the capture's real-time rate off esp_timer. The capture was generated by synth with
 * --pos-sigma 0, so the fixes carry no position noise and the on-device lap engine reproduces the
 * committed replay lap times (test/data/sim_capture.expected.json) within the +/-30 ms exit gate.
 *
 * The driver assigns each delivered fix a fresh mono_us (real device time at delivery) and leaves
 * valid = 0 for the pipeline to fill via the §6.5 rule -- exactly as a real driver hands over a
 * freshly assembled fix. gps_sim_venue_json() hands the pipeline the capture's synthetic venue
 * (same JSON string replay used for --venue-json), so device and replay share one venue.
 *
 * Once the capture is exhausted, the driver keeps delivering the last capture fix as a parked
 * bike (gspeed_mms = 0, everything else from that fix unchanged) at a fixed 1 Hz cadence instead
 * of going silent, so the pipeline still sees a still fix (ruling T9-R2, Plan 7 T9 fix 1).
 */
#include "hal/gps.h"
#include "sim_capture.h"
#include "core/core.h"

#include "esp_timer.h"

#include <stdio.h>
#include <string.h>

/* Power of 10 rule 5: per-module assertion code; file:line at the hook pins the exact check. */
#define GPS_SIM_ASSERT_CODE 0x0C40

/* Parked-phase cadence once the capture is exhausted (ruling T9-R2): 1 Hz, independent of the
 * capture's own SIM_FIX_RATE_HZ. */
#define SIM_PARK_PERIOD_US 1000000

static const gps_profile_t s_profile = {
    .max_rate_hz = SIM_FIX_RATE_HZ,
    .baud        = 38400,
    .has_pps     = 0,
    .name        = "sim",
};

static uint32_t s_idx;            /* next capture fix to deliver */
static bool     s_started;        /* the playback clock has been anchored */
static int64_t  s_t0_mono_us;     /* device mono time mapped to SIM_FIXES[0].gps_us */
static int64_t  s_last_frame_us;  /* mono time of the last delivered fix */
static uint32_t s_frames_ok;
static uint32_t s_parked;         /* count of delivered parked fixes; saturates at UINT32_MAX */

int gps_init(const gps_profile_t **out_profile)
{
    s_idx = 0;
    s_started = false;
    s_last_frame_us = 0;
    s_frames_ok = 0;
    s_parked = 0;
    if (out_profile) *out_profile = &s_profile;
    return 0;
}

int gps_configure(uint8_t rate_hz)
{
    (void)rate_hz;                /* the capture rate is fixed; nothing to push to a receiver */
    s_idx = 0;
    s_started = false;
    s_parked = 0;
    return 0;
}

/* Once the capture is exhausted, deliver the last capture fix again as a parked bike: same
 * position/accuracy/fix-type/sats/flags, gspeed_mms = 0, head_e5 unchanged (ruling T9-R2). Due
 * when the parked cadence has elapsed since the mono time of the previous delivery (whether that
 * was the last capture fix or an earlier parked fix); gps_us keeps advancing by
 * SIM_PARK_PERIOD_US per delivered fix off the last capture fix's gps_us so the monotonic-GPS-
 * time invariant downstream still holds. mono_us/valid/the frame bookkeeping follow the same
 * rule as every other delivered fix. */
static int deliver_parked(gps_fix_t *out, int64_t now)
{
    CORE_ASSERT_RET(out != NULL, GPS_SIM_ASSERT_CODE, -1);
    CORE_ASSERT_RET(s_idx >= SIM_FIX_COUNT, GPS_SIM_ASSERT_CODE, 0);

    if (now - s_last_frame_us < SIM_PARK_PERIOD_US) return 0;

    const sim_fix_t *s = &SIM_FIXES[SIM_FIX_COUNT - 1];
    if (s_parked < UINT32_MAX) s_parked++;

    memset(out, 0, sizeof *out);
    out->gps_us     = s->gps_us + (int64_t)s_parked * SIM_PARK_PERIOD_US;
    out->mono_us    = now;                                /* real arrival time on this board */
    out->lat_e7     = s->lat_e7;
    out->lon_e7     = s->lon_e7;
    out->alt_mm     = s->alt_mm;
    out->gspeed_mms = 0;                                  /* parked: no motion */
    out->head_e5    = s->head_e5;
    out->hacc_mm    = s->hacc_mm;
    out->sacc_mms   = s->sacc_mms;
    out->pdop_e2    = s->pdop_e2;
    out->fix_type   = s->fix_type;
    out->sats       = s->sats;
    out->flags      = s->flags;
    out->valid      = 0;                                  /* pipeline applies the §6.5 rule */

    s_last_frame_us = now;
    s_frames_ok++;
    return 1;
}

int gps_poll(gps_fix_t *out)
{
    CORE_ASSERT_RET(out != NULL, GPS_SIM_ASSERT_CODE, -1);

    int64_t now = esp_timer_get_time();
    if (!s_started) { s_started = true; s_t0_mono_us = now; }

    if (s_idx >= SIM_FIX_COUNT) return deliver_parked(out, now);  /* capture exhausted: park */

    /* Fix s_idx is due once real elapsed time has reached its offset from the first fix. */
    int64_t due_us = SIM_FIXES[s_idx].gps_us - SIM_FIXES[0].gps_us;
    if (now - s_t0_mono_us < due_us) return 0;

    /* Index invariant the array access below assumes: s_idx must stay within the capture. */
    CORE_ASSERT_RET(s_idx < SIM_FIX_COUNT, GPS_SIM_ASSERT_CODE, 0);
    const sim_fix_t *s = &SIM_FIXES[s_idx];
    memset(out, 0, sizeof *out);
    out->gps_us     = s->gps_us;
    out->mono_us    = now;                                /* real arrival time on this board */
    out->lat_e7     = s->lat_e7;
    out->lon_e7     = s->lon_e7;
    out->alt_mm     = s->alt_mm;
    out->gspeed_mms = s->gspeed_mms;
    out->head_e5    = s->head_e5;
    out->hacc_mm    = s->hacc_mm;
    out->sacc_mms   = s->sacc_mms;
    out->pdop_e2    = s->pdop_e2;
    out->fix_type   = s->fix_type;
    out->sats       = s->sats;
    out->flags      = s->flags;
    out->valid      = 0;                                  /* pipeline applies the §6.5 rule */

    s_last_frame_us = now;
    s_idx++;
    s_frames_ok++;
    return 1;
}

/* The sim path never ingests UART bytes; these are no-ops sufficient for the pipeline. */
int gps_feed_bytes(const uint8_t *buf, size_t n) { (void)buf; (void)n; return 0; }
int gps_set_power_mode(uint8_t mode)             { (void)mode; return 0; }
int gps_wake(void)                               { return 0; }
int gps_reinit_uart(uint32_t baud)               { (void)baud; return 0; }

int gps_get_version(char *buf, size_t n)
{
    if (!buf || n == 0) return -1;
    (void)snprintf(buf, n, "sim");
    return 0;
}

uint32_t gps_stats_frames_ok(void)  { return s_frames_ok; }
uint32_t gps_stats_frames_bad(void) { return 0; }
int64_t  gps_last_frame_mono_us(void) { return s_last_frame_us; }

/* The synthetic venue the capture was built around, as a JSON string. The pipeline parses it with
 * trk_from_json -- the same code path replay used for --venue-json -- so both share one venue. */
const char *gps_sim_venue_json(void) { return SIM_VENUE_JSON; }
