/* host/epd_panel.c -- SSD1680 panel capability table + selection (Plan 7 Task 4; epd_pure.h).
 * Pure/host-testable: no ESP-IDF dependency. On target the row is picked by the build's PANEL
 * flag (CFG_PANEL_WS213V4 in build_config.h, generated by the top-level CMakeLists.txt, §4.6);
 * the host test harness (test/CMakeLists.txt's test_epd_pure) has no build_config.h, so
 * EPD_FORCE_PANEL_213 selects the row directly there.
 */
#include "epd_pure.h"

/* The firmware build tree generates build_config.h; the host harness compiles this file without
 * it (same __has_include guard as components/core/tracks/trk_json.c). */
#if __has_include("build_config.h")
#include "build_config.h"
#endif

#if defined(EPD_FORCE_PANEL_213)
#define EPD_PANEL_IS_213 1
#elif defined(CFG_PANEL_WS213V4) && CFG_PANEL_WS213V4
#define EPD_PANEL_IS_213 1
#else
#define EPD_PANEL_IS_213 0
#endif

const epd_panel_t *epd_panel(void)
{
    static const epd_panel_t table[2] = {
        /* name        native_w native_h logical_w logical_h ram_w border lut_full lut_partial */
        { "ws213v4",   122,     250,     250,      122,      128,  0x05,  0xF7,    0xFF },
        { "ws29v2",    128,     296,     296,      128,      128,  0x05,  0xF7,    0xFF },
    };
    return &table[EPD_PANEL_IS_213 ? 0 : 1];
}
