/* devcontroller/components/webapi/include/status_json.h -- a PURE formatter for the GET
 * /api/status 200 (success) body (Plan 5.6 T3 fix 2).
 *
 * webapi.c's api_status() builds this JSON from a decoded lt_status_t plus the ages/logging flag
 * it reads from linkhost's (locked) stats cache; the string formatting itself has no IDF
 * dependency and no shared state, so it is split out here for a direct host test
 * (devcontroller/test/test_status_json.c), mirroring the existing linkhost_stream_to_json
 * precedent (linkhost_proto.h). IDF-free on purpose: only lt_status_t is pulled in, from
 * linkhost_proto.h.
 */
#ifndef STATUS_JSON_H
#define STATUS_JSON_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "linkhost_proto.h"   /* lt_status_t only */

#ifdef __cplusplus
extern "C" {
#endif

/* Formats the /api/status "connected":true body into buf[cap] as NUL-terminated JSON, in exactly
 * the field order/conversions api_status has always used: proto, state, flags, batt_pct, batt_mv,
 * free_kb, sessions, fw, then the caller's pre-formatted flash-error fragment `ferr` (either "" or
 * the exact ",\"flash_err\":\"...\"" api_status already builds, spliced in verbatim), then
 * status_age_ms/stream_age_ms/logging. status_age_ms/stream_age_ms pass through unchanged
 * (including -1 for "never seen" -- see linkstats_age_ms). `st->fw` is escaped (M5, final review)
 * before being spliced in -- it is decoded off the wire, not generated by this side, so a '"' or
 * '\\' byte in it must not be allowed to break out of the JSON string it is embedded in. Returns
 * the body length written (excluding the NUL), or -1 if `cap` is too small for the formatted body
 * -- buf's contents are then whatever snprintf partially wrote and MUST NOT be sent (never a
 * silently truncated body). */
int status_json_format(char *buf, size_t cap, const lt_status_t *st, const char *ferr,
                       int64_t status_age_ms, int64_t stream_age_ms, bool logging);

#ifdef __cplusplus
}
#endif

#endif /* STATUS_JSON_H */
