#!/usr/bin/env python3
"""Generate components/core/tracks/trk_bundled.c from tools/tracks/*.json (spec §10.2)."""
import json, sys, argparse, math, pathlib

MAX_LAYOUTS, MAX_SECTORS = 8, 8

def dist_m(a, b):
    R = 6371008.8
    p1, p2 = math.radians(a[0]), math.radians(b[0])
    dp, dl = p2 - p1, math.radians(b[1] - a[1])
    h = math.sin(dp/2)**2 + math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*R*math.asin(math.sqrt(h))

def check_line(line, what, name):
    assert isinstance(line, list) and len(line) == 2, f"{name}: {what} must be [[lat,lon],[lat,lon]]"
    for p in line:
        assert isinstance(p, list) and len(p) == 2, f"{name}: {what} point"
    L = dist_m(line[0], line[1])
    # a line whose endpoints coincide has no direction, so §6.4 can never detect a crossing
    assert L >= 1.0, f"{name}: {what} endpoints only {L:.2f} m apart (degenerate line)"
    assert 10 <= L <= 60, f"{name}: {what} length {L:.1f} m outside 10–60 m"

def expand(v):
    assert 1 <= v["id"] <= 999, f"{v['name']}: bundled id must be 1..999"
    assert 1 <= len(v["layouts"]) <= MAX_LAYOUTS
    lids = [L["id"] for L in v["layouts"]]
    assert len(lids) == len(set(lids)), f"{v['name']}: duplicate layout ids {lids}"
    first = v["layouts"][0]
    for k, L in enumerate(v["layouts"]):
        assert L["dir"] in (1, -1)
        if L["sf"] == "same":
            assert k > 0; L["sf"] = first["sf"]
        check_line(L["sf"], "sf", v["name"])
        secs = L.get("sectors", [])
        if secs == "reverse":
            assert k > 0; secs = list(reversed(first.get("sectors", [])))
        assert len(secs) <= MAX_SECTORS
        for s in secs: check_line(s, "sector", v["name"])
        L["sectors"] = secs
        L.setdefault("length_m", 0)
    return v

def c_str(s, n):
    assert len(s) < n, f"string too long: {s}"
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def c_line(l):
    return f"{{ {{ {l[0][0]!r}, {l[0][1]!r} }}, {{ {l[1][0]!r}, {l[1][1]!r} }} }}"

def emit(venues, out):
    w = out.write
    w("/* GENERATED by tools/tracks/gen_tracks.py — do not edit. */\n#include \"core/trk.h\"\n\n")
    w("const trk_venue_t trk_bundled[] = {\n")
    for v in venues:
        flags = 0 if v.get("verified", False) else 1
        w(f"  {{ .id = {v['id']}, .name = {c_str(v['name'], 32)}, .lat = {v['lat']!r}, .lon = {v['lon']!r}, .radius_m = {v.get('radius_m', 2000)}, .flags = {flags}, .n_layouts = {len(v['layouts'])}, .layouts = {{\n")
        for L in v["layouts"]:
            w(f"    {{ .id = {L['id']}, .name = {c_str(L['name'], 24)}, .sf = {c_line(L['sf'])}, .dir_sign = {L['dir']}, .n_sectors = {len(L['sectors'])}, .sectors = {{\n")
            for s in L["sectors"]:
                w(f"      {c_line(s)},\n")
            w(f"    }}, .length_m = {L['length_m']} }},\n")
        w("  } },\n")
    w("};\n")
    w(f"const uint16_t trk_bundled_count = {len(venues)};\n")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("-o", "--output", required=True)
    a = ap.parse_args()
    venues = [expand(json.load(open(f))) for f in sorted(a.files)]
    ids = [v["id"] for v in venues]
    assert len(ids) == len(set(ids)), "duplicate venue ids"
    with open(a.output, "w") as out:
        emit(venues, out)
    print(f"wrote {a.output}: {len(venues)} venues")

if __name__ == "__main__":
    main()
