#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "unity.h"
#include "esp_pthread.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

/* Each host test file is compiled with main/setUp/tearDown renamed per suite (see CMakeLists.txt).
 * Unity calls the global setUp()/tearDown(); these dispatch to the suite currently running. */
typedef void (*hook_t)(void);
static hook_t cur_setup, cur_teardown;
void setUp(void) { if (cur_setup) cur_setup(); }
void tearDown(void) { if (cur_teardown) cur_teardown(); }

/* suites_gen.h is generated by CMakeLists.txt from the same test/test_*.c glob that builds the
 * wrappers, one SUITE(name) line per file, so a new suite is always declared, built into the table
 * below and run -- it cannot be linked but silently skipped. */
#define SUITE(name) int run_test_##name(void); void setUp_test_##name(void); void tearDown_test_##name(void);
#include "suites_gen.h"
#undef SUITE

typedef struct { const char *name; int (*run)(void); hook_t setup, teardown; } suite_t;
#define SUITE(name) { #name, run_test_##name, setUp_test_##name, tearDown_test_##name },
static const suite_t suites[] = {
#include "suites_gen.h"
};
#undef SUITE

/* The suites above run in app_main's 40 KB task, which says nothing about whether the core fits an
 * ordinary app task. The two suites that drive the deepest core call chains (cfg walks a JSON tree,
 * trk parses and re-serialises a venue) are rerun in a 6 KB task -- the stack size spec §4.3 budgets
 * for the conn task -- and the remaining headroom is reported. */
#define STACK6K_BYTES 6144
static volatile int      stack6k_failed = -1;      /* -1 = not finished yet */
static volatile unsigned stack6k_free_bytes;

static void stack6k_task(void *arg)
{
    (void)arg;
    int failed = 0;
    for (size_t i = 0; i < sizeof suites / sizeof suites[0]; i++) {
        if (strcmp(suites[i].name, "cfg") != 0 && strcmp(suites[i].name, "trk") != 0) continue;
        cur_setup = suites[i].setup; cur_teardown = suites[i].teardown;
        if (suites[i].run() != 0) failed++;
    }
    stack6k_free_bytes = (unsigned)uxTaskGetStackHighWaterMark(NULL);
    printf("--- stack6k cfg+trk: %s --- (%u B stack, %u B never used)\n",
           failed ? "FAIL" : "OK", (unsigned)STACK6K_BYTES, stack6k_free_bytes);
    stack6k_failed = failed;
    vTaskDelete(NULL);
}

void app_main(void)
{
    esp_pthread_cfg_t pcfg = esp_pthread_get_default_config();
    pcfg.stack_size = 6144; pcfg.prio = 5;
    pcfg.pin_to_core = 1;           /* app_main is pinned to core 0; spinning test threads must not starve it */
    esp_pthread_set_cfg(&pcfg);

    const size_t n = sizeof suites / sizeof suites[0];
    int failed = 0;
    printf("\n=== core_selftest: %u suites, free heap %u ===\n", (unsigned)n, (unsigned)esp_get_free_heap_size());
    for (size_t i = 0; i < n; i++) {
        cur_setup = suites[i].setup; cur_teardown = suites[i].teardown;
        printf("--- %s ---\n", suites[i].name);
        int64_t t0 = esp_timer_get_time();
        int r = suites[i].run();
        printf("--- %s: %s (%lld ms) ---\n", suites[i].name, r == 0 ? "OK" : "FAIL", (long long)((esp_timer_get_time() - t0) / 1000));
        if (r != 0) failed++;
        vTaskDelay(pdMS_TO_TICKS(20));
    }

    if (xTaskCreatePinnedToCore(stack6k_task, "stack6k", STACK6K_BYTES, NULL, 5, NULL, 1) != pdPASS) {
        printf("--- stack6k cfg+trk: FAIL --- (task could not be created)\n");
        stack6k_failed = 1;
    }
    while (stack6k_failed < 0) vTaskDelay(pdMS_TO_TICKS(50));

    int bad = failed + (stack6k_failed != 0 ? 1 : 0);
    printf("=== core_selftest RESULT: %s, %d failing suites, stack6k %s (%u B free), free heap %u, min free %u ===\n",
           bad ? "FAIL" : "PASS", failed, stack6k_failed == 0 ? "OK" : "FAIL", stack6k_free_bytes,
           (unsigned)esp_get_free_heap_size(), (unsigned)esp_get_minimum_free_heap_size());
    for (;;) vTaskDelay(pdMS_TO_TICKS(10000));
}
