/* GENERATED by tools/tracks/gen_tracks.py — do not edit. */
#include "core/trk.h"

const trk_venue_t trk_bundled[] = {
  { .id = 6, .name = "Killarney", .lat = -33.8567, .lon = 18.517, .radius_m = 2000, .flags = 1, .n_layouts = 4, .layouts = {
    { .id = 1, .name = "Full", .sf = { { -33.8578, 18.5152 }, { -33.85795, 18.51535 } }, .dir_sign = 1, .n_sectors = 2, .sectors = {
      { { -33.853, 18.519 }, { -33.85315, 18.51925 } },
      { { -33.8595, 18.521 }, { -33.85965, 18.5208 } },
    }, .length_m = 3267 },
    { .id = 2, .name = "Full Reverse", .sf = { { -33.8578, 18.5152 }, { -33.85795, 18.51535 } }, .dir_sign = -1, .n_sectors = 2, .sectors = {
      { { -33.8595, 18.521 }, { -33.85965, 18.5208 } },
      { { -33.853, 18.519 }, { -33.85315, 18.51925 } },
    }, .length_m = 3267 },
    { .id = 3, .name = "Short", .sf = { { -33.8578, 18.5152 }, { -33.85795, 18.51535 } }, .dir_sign = 1, .n_sectors = 1, .sectors = {
      { { -33.853, 18.519 }, { -33.85315, 18.51925 } },
    }, .length_m = 2500 },
    { .id = 4, .name = "Short Reverse", .sf = { { -33.8578, 18.5152 }, { -33.85795, 18.51535 } }, .dir_sign = -1, .n_sectors = 1, .sectors = {
      { { -33.853, 18.519 }, { -33.85315, 18.51925 } },
    }, .length_m = 2500 },
  } },
  { .id = 2, .name = "Zwartkops", .lat = -25.8103, .lon = 28.1497, .radius_m = 2000, .flags = 1, .n_layouts = 1, .layouts = {
    { .id = 1, .name = "Full", .sf = { { -25.8095, 28.1485 }, { -25.80965, 28.1487 } }, .dir_sign = 1, .n_sectors = 1, .sectors = {
      { { -25.812, 28.151 }, { -25.81215, 28.1508 } },
    }, .length_m = 2400 },
  } },
};
const uint16_t trk_bundled_count = 2;
